name: Test Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Install NodeJS
        uses: actions/setup-node@v4.0.4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test



